github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/onlyfans-downloader",
"https://whop.com/serp-downloaders/onlyfans-downloader/",
"https://serp.co/products/beeg-video-downloader/reviews/",
]
